import {
  pgTable,
  serial,
  text,
  timestamp,
  boolean,
  integer,
} from "drizzle-orm/pg-core";

/**
 * SCIENCE_INGEST TABLE
 * Primary storage for raw, unverified data harvested by Hermie
 */
export const scienceIngest = pgTable("science_ingest", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  doi: text("doi"),
  abstract: text("abstract"),
  sourceUrl: text("source_url"),
  keywords: text("keywords"), // JSON stringified array
  biomarkers: text("biomarkers"), // JSON stringified array (cortisol, HRV, inflammatory markers, etc.)
  processed: boolean("processed").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

/**
 * CORRELATIONS TABLE
 * High-value relational rows generated by Jimmy
 * Pairs scripture to scientific data
 */
export const correlations = pgTable("correlations", {
  id: serial("id").primaryKey(),
  scienceIngestId: integer("science_ingest_id").references(
    () => scienceIngest.id,
  ),
  title: text("title").notNull(),
  category: text("category").notNull(), // e.g., "NERVOUS SYSTEM // FORGIVENESS"

  // Biblical Component
  bibleVerse: text("bible_verse").notNull(), // e.g., "Proverbs 14:30"
  scriptureText: text("scripture_text").notNull(),

  // Scientific Component
  scientificMechanism: text("scientific_mechanism").notNull(), // e.g., "Vagus Nerve Activation"
  physiologicalBenefit: text("physiological_benefit").notNull(),
  biomarkerData: text("biomarker_data"), // JSON stringified object with specific metrics

  // Community Engagement
  socialHook: text("social_hook").notNull(), // Jimmy's community question

  verified: boolean("verified").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

/**
 * REFLECTIONS TABLE
 * Community bonding layer tracking user responses to social prompts
 */
export const reflections = pgTable("reflections", {
  id: serial("id").primaryKey(),
  correlationId: integer("correlation_id")
    .references(() => correlations.id)
    .notNull(),
  userId: text("user_id"), // Optional: for authenticated users
  content: text("content").notNull(),
  isPublic: boolean("is_public").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type ScienceIngest = typeof scienceIngest.$inferSelect;
export type NewScienceIngest = typeof scienceIngest.$inferInsert;

export type Correlation = typeof correlations.$inferSelect;
export type NewCorrelation = typeof correlations.$inferInsert;

export type Reflection = typeof reflections.$inferSelect;
export type NewReflection = typeof reflections.$inferInsert;
